name: 'Close stale issues and PRs'
on: workflow_dispatch # only run on demand in Actions

jobs:
  stale:
    name: 'Close stale issues and PRs'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Please add a comment if this is still an ongoing issue; otherwise this issue will be automatically closed in 7 days.'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Please add a comment if this PR is still needed; otherwise this PR will be automatically closed in 7 days.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-message: 'This issue is being closed due to inactivity. Please see our [Honeycomb OSS Lifecyle and Practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md).'
          close-pr-message: 'This PR is being closed due to inactivity. Please see our [Honeycomb OSS Lifecyle and Practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md).'
          days-before-pr-stale: 30
          days-before-issue-stale: 14
          days-before-close: 7
